config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users

  resources :users do
  	resources :charges, only: [:create]
  	resources :carts, only: [:show,:destroy,:create]	
  	resources :avatar, only: [:create]
  end
  resources :items
  resources :orders


  namespace :admin do
    root 'admins#index'
    resources :admins
    resources :users
    resources :items
    resources :orders
  end
  resources :teams, only:[:index]
  resources :contacts, only:[:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :carts
	has_many :users, through: :cart
	has_many :orders

  	validates :title, presence: true,
	length: {minimum: 5, maximum: 140},
	uniqueness: true

	validates :descript, presence: true,
	length: { minimum: 5, maximum: 1000},
	uniqueness: true

	validates :price, presence: true,
	numericality: { greater_than: 1, less_than: 1000}
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :items
	belongs_to :user

	after_create :customer_email 
	after_create :administrator_email

	def customer_email
  	  OrderMailer.customer_email(self).deliver_now
  	end

  	def admnistrator_email
  	  OrderMailer.administrator_email(self).deliver_now
  	end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :items, through: :cart
  has_one_attached :image_url
  has_one_attached :avatar

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  #validates :first_name, presence: true
  #validates :last_name, presence: true
end

app/controllers/avatar_controller.rb
class AvatarController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    @cart = Cart.where(user_id: params[:user_id])
    @item = Item.all
    @order = Order.new
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)

    @cart = Cart.create(user_id: current_user.id, item_id: params[:item_id])
    #Creates a new cart that keeps the same id (user_id) which means that there will be only one cart
    redirect_to root_path
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    @cart = Cart.find(params[:item_id])
    @cart.destroy
    redirect_to root_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
    @cart = Cart.all
    @item = Item.find(params[:id])
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

def index
end 



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
    before_action :connected_user, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user, only: [:show, :edit, :update, :destroy]

	def index
	# Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
	end

	def show
	# Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
		@user = User.find(params[:id])
	end

	def new
	end

	def create
	end

	def edit
	end

	def update
	end

	def destroy
	end

  private

  def connected_user
    if current_user.nil?
      flash[:loggin_needed] = "Please log in."
      redirect_to root_path
    end
  end

  def authenticate_user
    if current_user.id != User.find(params[:id]).id
      flash[:bad_user] = "Please log in."
      redirect_to root_path
    end
  end



end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatar_helper.rb
module AvatarHelper
end

app/helpers/bases_helper.rb
module BasesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/admin/admins/index.html.erb
<div class="container text-center" style= "margin-top: 120px;">
  <h3 class="title">Bienvenue <%= current_user.first_name %></h3>
  <p class="description">Que veut tu faire ?</p>
</div>
<br><br><br>
<div class="container">
<div class="card-deck">
<div class="card text-center" style="width: 20rem;">
  <div class="card-body">
    <h4 class="card-title">User</h4>
    <p class="card-text"></p>
    <a href="<%= admin_users_path %>" class="btn btn-primary">Suite</a>
  </div>
</div>
<div class="card text-center" style="width: 20rem;">
  <div class="card-body">
    <h4 class="card-title">Items</h4>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
</div>
<br><br>
<div class="card-deck">
<div class="card text-center" style="width: 20rem;">
  <div class="card-body">
    <h4 class="card-title">Orders</h4>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
<div class="card text-center" style="width: 20rem;">
  <div class="card-body">
    <h4 class="card-title"></h4>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
</div>
</div>
<br><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Katchup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Fonts and icons -->
    <script src="https://kit.fontawesome.com/2f609438b2.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <!-- Fonts and icons End -->

    <%= favicon_link_tag asset_path('cat.ico') %>

  </head>

  <body>
    <%@cart = Cart.all%>
    <% if user_signed_in? %>
      <%@nombreItem = Cart.where(user_id:current_user.id)%>
    <%end%>

    <!-- NavBar -->


    <nav class="navbar navbar-expand-lg fixed-top">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">Katchup</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#"><span class="sr-only">(current)</span>Catégories</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%=link_to "L'équipe", teams_path %> </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%=link_to "Nous contacter", contacts_path%> </a>
          </li>
          
          <% if user_signed_in? %>
            <li class="nav-item">
                 <a class="nav-link" href="<%=user_cart_path(current_user,1)%>">Panier <%=@nombreItem.count%></a>
            </li>
          <%end%>
          
          <li class="nav-item dropdown navbar-toggler-right">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Mes options
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <% if user_signed_in? %>
              <a class="dropdown-item" href="<%=user_path(current_user)%>">Mon profil</a>
              <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class:"dropdown-item"%>
              <%else%>
              <a class="dropdown-item" href="<%=new_user_session_path%>">Se connecter</a>
              <a class="dropdown-item" href="<%=new_user_registration_path%>">S'inscrire</a>
              <%end%>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- End NavBar -->


    <%= yield %>
  </body>
  <!-- Footer -->
  <footer class="page-footer bg-primary text-white">
<br>
    <!-- Footer Links -->
    <div class="container text-center text-md-left mt-5">

      <!-- Grid row -->
      <div class="row mt-3">

        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

          <!-- Content -->
          <h6 class="text-uppercase font-weight-bold">Katchup Company</h6>
          <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>Katchup est une entreprise connue dans le monde entier, nous vendons des photos de chats de qualité, que personne ne peut égaler.</p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Produits</h6>
          <hr class="accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <a class="text-white" href="https://pixabay.com/fr/images/search/chat%20bleu/">Chat bleu</a>
          </p>
          <p>
            <a class="text-white" href="https://pixabay.com/fr/images/search/chat%20rouge/">Chat rouge</a>
          </p>
          <p>
            <a class="text-white" href="https://pixabay.com/fr/images/search/chat%20vert/">Chat vert</a>
          </p>
          <p>
            <a class="text-white" href="https://pixabay.com/fr/images/search/chat%20bott%C3%A9/">Chat botté</a>
          </p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Liens utiles</h6>
          <hr class="accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <a class="text-white" href="<%=new_user_session_path%>">Mon profil</a>
          </p>
          <p>
            <a class="text-white" href="<%=new_user_session_path%>">Envoyez vos photos</a>
          </p>
          <p>
            <a class="text-white" href="https://www.youtube.com/watch?v=ZM3e5Rj8BCE">Signalez un problème</a>
          </p>
          <p>
            <a class="text-white" href="https://www.youtube.com/watch?v=2Q_ZzBGPdqE">Help</a>
          </p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Contact</h6>
          <hr class="accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <i class="fas fa-home"></i> Montpellier, MTP 34000, FR</p>
          <p>
            <i class="fas fa-envelope mr-3"></i> thp.mtp@gmail.com </p>
          <p>
            <i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
          <p>
            <i class="fas fa-print mr-3"></i> + 01 234 567 89</p>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/">| THP MTP</a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->
</html>