config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users

  resources :users do
  	resources :charges, only: [:create]
  	resources :carts, only: [:show,:destroy,:create]	
  	resources :avatar, only: [:create]
  end
  resources :items
  resources :orders


  namespace :admin do
    root 'admins#index'
    resources :admins
    resources :users
    resources :items
    resources :orders
  end
  resources :teams, only:[:index]
  resources :contacts, only:[:index]
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	belongs_to :item
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    @cart = Cart.where(user_id: params[:user_id])
    @item = Item.all
    @order = Order.new
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)

    @cart = Cart.create(user_id: current_user.id, item_id: params[:item_id])
    #Creates a new cart that keeps the same id (user_id) which means that there will be only one cart
    redirect_to root_path
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    @cart = Cart.find(params[:item_id])
    @cart.destroy
    redirect_to root_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<div style="margin-top:160px; margin-bottom: 120px;">


<%= form_tag user_charges_path(params[:user_id]) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    	<div class="row justify-content-center">
  		<div class="col-sm-6 pt-2">
  			<div class="card">
  				<div class="card-body">
  					<h5 class="card-title">Panier </h5>
            <%prix_total = 0%>
            <%@cart.each do |t|%>
             <hr>
              <p class="card-text">Title : <%=@item.find(t.item_id).title%></p>
              <p class="card-text">Prix : <%=@item.find(t.item_id).price%>€</p>
              <%= link_to "Supprimez", user_cart_path(user_id:current_user.id, item_id: t.id),  method: :delete, class:"btn btn-outline-danger" %>
              <%prix_total += @item.find(t.item_id).price%>
            <%end%>
            <%if prix_total != 0%>
                <p class="card-text">Prix total : <%=prix_total%>€</p>
              <%else%>
                <p class="card-text">Panier vide</p>
            <%end%>
            <%if prix_total != 0%>
                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                    data-description="Inscription à l'événement"
                    data-amount="<%=prix_total * 100%>"
                    data-locale="auto"></script>
            <%end%>
  				</div>
  			</div>
  		</div>
  	</div>
  </article>
<%end%>

</div>