config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users

  resources :users do
  	resources :charges, only: [:create]
  	resources :carts, only: [:show,:destroy,:create]	
  	resources :avatar, only: [:create]
  end
  resources :items
  resources :orders


  namespace :admin do
    root 'admins#index'
    resources :admins
    resources :users
    resources :items
    resources :orders
  end
  resources :teams, only:[:index]
  resources :contacts, only:[:index]
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :carts
	has_many :users, through: :cart
	has_many :orders

  	validates :title, presence: true,
	length: {minimum: 5, maximum: 140},
	uniqueness: true

	validates :descript, presence: true,
	length: { minimum: 5, maximum: 1000},
	uniqueness: true

	validates :price, presence: true,
	numericality: { greater_than: 1, less_than: 1000}
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
    @cart = Cart.all
    @item = Item.find(params[:id])
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<body>



<div class="page-header section-dark " style=" background-attachment: fixed; background-image: url('https://cdn.pixabay.com/photo/2015/11/16/14/43/cat-1045782_960_720.jpg')">
    <div class="content-center">
      <div class="container">
        <div class="text-center">

          <h1 class="ml11" style="text-align:center; font-size:88px; font-weight:bold; padding-top:40px;">
           <span class="text-wrapper">
             <span class="line line1"></span>
             <span class="letters" style="color:white;">Katchup !</span>
           </span>
         </h1>

         <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>

        </div>
        <h2 class="presentation-subtitle text-center" style="font-size:38px; font-weight:bold;">Deux yeux bleus, des moustaches trop mims et un pelage brillant, nos chats sont plus beaux que tu ne le seras jamais. Désolé.</h2>
      </div>
    </div>
    </div>

  <div class="site-blocks-cover overlay" style="" data-aos="fade" data-stellar-background-ratio="0.5">
    <div class="container">
      <div class="row align-items-center justify-content-center text-center">
        <div class="col-md-10">
          <div class="row justify-content-center mb-4">
            <div class="col-md-8 text-center">
              <h1 class="title text-primary">Ajouts récents</h1>
              <p data-aos="fade-up" data-aos-delay="100">Parcourez les photos de nos chatons!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<!-- Cards -->

<div class="card-deck text-center mx-auto" style="width: 80%;">
  <% @items.each_with_index do |t, index| %>
<%  if index < 5 %>
  <div class="card" style="">
  <img class="card-img-top" src="<%= t.image_url %>" alt="Card image cap">
  <div class="card-body">
    <h4 class="card-title"><%= t.title %></h4>
    <p class="card-text"></p>
    <a href="<%= item_path(t) %>" class="btn btn-primary">Voir plus </a>
  </div>
</div>
<% end %>
<% end %>
</div>



<!-- Cards Deck End  -->
<br><br>
<div class="site-blocks-cover overlay" style="background-image: url('');" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">
      <div class="col-md-10">
        <div class="row justify-content-center mb-4">
          <div class="col-md-8 text-center">
            <h1 class="title text-primary">Les plus populaires</h1>
            <p data-aos="fade-up" data-aos-delay="100">Vous ne savez pas laquelle choisir? Parcourez les photos les plus populaires!</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Cards -->

<div class="card-deck text-center mx-auto" style="width: 80%;">
  <% @items.each_with_index do |t, index| %>
<%  if index > 5 and index < 10%>
  <div class="card" style="">
  <img class="card-img-top" src="<%= t.image_url %>" alt="Card image cap">
  <div class="card-body">
    <h4 class="card-title"><%= t.title %></h4>
    <p class="card-text"></p>
    <a href="<%= item_path(t) %>" class="btn btn-primary">Voir plus </a>
  </div>
</div>
<% end %>
<% end %>
</div>

<!-- Cards Deck End  -->
<br><br>
<div class="site-blocks-cover overlay" style="background-image: url('');" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">
      <div class="col-md-10">
        <div class="row justify-content-center mb-4">
          <div class="col-md-8 text-center">
            <h1 class="title text-primary">Encore disponible !</h1>
            <p data-aos="fade-up" data-aos-delay="100">Faites vite votre choix, elles ne resteront pas longtemps!</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Cards -->

<div class="card-deck text-center mx-auto" style="width: 80%;">
  <% @items.each_with_index do |t, index| %>
  <% if index > 10 and index < 15%>
  <div class="card" style="">
    <img class="card-img-top" src="<%= t.image_url %>" alt="Card image cap">
    <div class="card-body">
      <h4 class="card-title"><%= t.title %></h4>
      <p class="card-text"></p>
      <a href="<%= item_path(t) %>" class="btn btn-primary">Voir plus </a>
  </div>
</div>
<% end %>
<% end %>
</div>

<!-- Cards Deck End -->


<div style="background-color:#6DD3D6; opacity:90%; transform:skewY(-1deg); margin-bottom:40px; margin-top:80px; ">
  <div class="container text-center py-4" style="transform:skewY(1deg);">

    <h3 style="padding-top:20px; padding-bottom:20px; color:white; font-size:32px;"> Vous ne faites pas encore partie de la communauté des Cats'Loveurz ? </h2>
    <%= link_to "S'inscire", new_user_path,  method: :post, class:"btn btn-outline-primary", style:"background-color:white; margin-bottom:20px;" %>

  </div>
</div>

<!-- Ask Questions -->
<br><br>
  <div class="site-section">
    <div class="container">
      <div class="row justify-content-center mb-5">
        <div class="col-md-7 text-center border-primary">
          <h2 class="title text-primary">Questions fréquentes</h2>
          <p class="color-black-opacity-5">Katchup répond à vos questions !</p>
        </div>
      </div>


      <div class="row justify-content-center">
        <div class="col-8">
          <div class="border p-3 rounded mb-2">
            <a data-toggle="collapse" href="#collapse-1" role="button" aria-expanded="false" aria-controls="collapse-1" class="accordion-item h5 d-block mb-0">Comment avons-nous toutes ces photos de chats ?</a>

            <div class="collapse" id="collapse-1">
              <div class="pt-2">
                <p class="mb-0">Nous avons un très grand jardin qui nous permet d'accueillir des millions voire des milliards de chats. Nous avons arrêté de compter car il y en a beaucoup trop, mais ils sont très mignons en tous cas.</p>
              </div>
            </div>
          </div>

          <div class="border p-3 rounded mb-2">
            <a data-toggle="collapse" href="#collapse-4" role="button" aria-expanded="false" aria-controls="collapse-4" class="accordion-item h5 d-block mb-0">Y a-t-il des chats comme ça dans ma ville ?</a>

            <div class="collapse" id="collapse-4">
              <div class="pt-2">
                <p class="mb-0">Certains de nos chats sont très spéciaux car nous les fabriquons à la main, ce sont des races inexistantes sauf chez nous, ce qui rend nos photos resplendissantes !</p>
              </div>
            </div>
          </div>

          <div class="border p-3 rounded mb-2">
            <a data-toggle="collapse" href="#collapse-2" role="button" aria-expanded="false" aria-controls="collapse-2" class="accordion-item h5 d-block mb-0">Vos photos sont-elles gratuites ?</a>

            <div class="collapse" id="collapse-2">
              <div class="pt-2">
                <p class="mb-0">Nos photos ne sont pas gratuites, elles sont à des prix abordables pour tous...</p>
              </div>
            </div>
          </div>

          <div class="border p-3 rounded mb-2">
            <a data-toggle="collapse" href="#collapse-3" role="button" aria-expanded="false" aria-controls="collapse-3" class="accordion-item h5 d-block mb-0">Vendez-vous vos chats ?</a>

            <div class="collapse" id="collapse-3">
              <div class="pt-2">
                <p class="mb-0">Possédant un grand jardin nous préférons garder nos millions de chats.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br><br>
<!-- Ask Questions End  -->

  <div class="py-5">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h2 class="title text-primary">Pas encore inscrit ? Créé ton compte !</h2>
          <p class="mb-4 lead text-white-opacity-05"></p>
          <br>
          <button type="button" class="btn btn-outline-primary btn-round btn-lg">S'inscrire</button>
        </div>
      </div>
    </div>
  </div>
  <br><br>




</body>




<style>


    .ml11 {
  font-weight: 700;
  font-size: 3.5em;
}
.ml11 .text-wrapper {
  position: relative;
  display: inline-block;
  padding-top: 0.1em;
  padding-right: 0.05em;
  padding-bottom: 0.15em;
}
.ml11 .line {
  opacity: 0;
  position: absolute;
  left: 0;
  height: 100%;
  width: 3px;
  background-color: #fff;
  transform-origin: 0 50%;
}
.ml11 .line1 {
  top: 0;
  left: 0;
}
.ml11 .letter {
  display: inline-block;
  line-height: 1em;
  }
</style>

<script type="text/javascript">
  // Wrap every letter in a span
  var textWrapper = document.querySelector('.ml11 .letters');
  textWrapper.innerHTML = textWrapper.textContent.replace(/([^\x00-\x80]|\w)/g, "<span class='letter'>$&</span>");
  anime.timeline({loop: true})
    .add({
      targets: '.ml11 .line',
      scaleY: [0,1],
      opacity: [0.5,1],
      easing: "easeOutExpo",
      duration: 700
    })
    .add({
      targets: '.ml11 .line',
      translateX: [0, document.querySelector('.ml11 .letters').getBoundingClientRect().width + 10],
      easing: "easeOutExpo",
      duration: 700,
      delay: 100
    }).add({
      targets: '.ml11 .letter',
      opacity: [0,1],
      easing: "easeOutExpo",
      duration: 600,
      offset: '-=775',
      delay: (el, i) => 34 * (i+1)
    }).add({
      targets: '.ml11',
      opacity: 0,
      duration: 1000,
      easing: "easeOutExpo",
      delay: 1000
    });
</script>

app/views/items/show.html.erb
<!DOCTYPE html>
<html>



	<body>

			<div class="jumbotron jumbotron-fluid" style="background-image:url('<%=@item.image_url%>'); background-repeat:no-repeat; background-size:cover; background-position:center; background-attachment:fixed; height:300px;">

			 	<div class="container">
			    <h1 class="display-4" style="color:white; font-weight:bold; font-size:68px;"><%= @item.title %></h1>
			    <p class="lead" style="color:white; font-weight:bold; font-size:28px;">C'est le plus Miaw-gnon de tous les kat !</p>
			  </div>

			</div>


			<div class="row justify-content-center" style="margin-top:40px;  padding-bottom:120px;">
				<div class="card">

					<div class="card-body  container row">

						<div class="col-4">

							<img src="<%= @item.image_url %>" class="card card-body" style="border-radius:10px;">
						</div>

						<div class="col">

							<h2 class="card-title" style="padding-top:20px;"><%=@item.title%></h2><hr>
							<p class="card-text"><strong>Description :</strong> <%=@item.descript%></p>
							<p class="card-text"><small>Prix : <%=@item.price%>€</small></p>
							<% if user_signed_in? %>
								<%= link_to "Ajouter au panier", user_carts_path(user_id:current_user.id, item_id:@item.id),  method: :post, class:"btn btn-outline-primary" %>
							<%end%>
							<%= link_to "Retour à la liste des articles", root_path,  class:"btn btn-outline-danger", style:"opacity:70%;" %>
							<br><br>
							<p> <span class="badge badge-primary"> <%=@cart.where(item_id:@item.id).count%> </span> Ils nous ont fait confiance ♡ </p>

						</div>


					</div>
				</div>
			</div>





	</body>
</html>