config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users

  resources :users do
  	resources :charges, only: [:create]
  	resources :carts, only: [:show,:destroy,:create]	
  	resources :avatar, only: [:create]
  end
  resources :items
  resources :orders


  namespace :admin do
    root 'admins#index'
    resources :admins
    resources :users
    resources :items
    resources :orders
  end
  resources :teams, only:[:index]
  resources :contacts, only:[:index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :items, through: :cart
  has_one_attached :image_url
  has_one_attached :avatar

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  #validates :first_name, presence: true
  #validates :last_name, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BasesController

	def index
		@users = User.all
	end

	def edit
			@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
      if @user.update(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], is_admin: params[:is_admin])
        flash[:success] = "L'utilisateur a bien etait modifier !"
        redirect_to admin_users_path
      else
        render :edit
      end
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
    before_action :connected_user, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user, only: [:show, :edit, :update, :destroy]

	def index
	# Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
	end

	def show
	# Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
		@user = User.find(params[:id])
	end

	def new
	end

	def create
	end

	def edit
	end

	def update
	end

	def destroy
	end

  private

  def connected_user
    if current_user.nil?
      flash[:loggin_needed] = "Please log in."
      redirect_to root_path
    end
  end

  def authenticate_user
    if current_user.id != User.find(params[:id]).id
      flash[:bad_user] = "Please log in."
      redirect_to root_path
    end
  end



end

app/views/admin/users/edit.html.erb
<style>

body {
  background-image : url('https://cdn.pixabay.com/photo/2015/11/16/14/43/cat-1045782_960_720.jpg');
  image-repeat:no-repeat;
  background-size:cover;
  background-attachment:fixed;
  height:30em;
}

</style >

<body>

<div class="container card card-body" style="padding-bottom:40px; border-radius:20px; background-color:white; opacity:96%; margin-top:80px; margin-bottom:80px;">
  <div class="row">
    <div class="col-md-6 offset-md-3">

      <h2 class="title"> Modifier un utilisateur</h2>
          <%= form_tag url_for(action: 'update'), method: "put", multipart: true do %>

            <%= label_tag "Image de l'utilisateur" %><br />
            <%= file_field_tag :avatar %>
            <br /> <br />


            <%= label_tag 'first_name' %>
            <%= text_field_tag 'first_name', @user.first_name, class: "form-control" %>
            <br /> <br />

            <%= label_tag 'last_name' %>
            <%= text_field_tag 'last_name', @user.last_name, class: "form-control" %>
            <br /> <br />

            <%= label_tag 'email' %>
            <%= text_field_tag 'email', @user.email, class: "form-control" %>
            <br /> <br />

            <%= label_tag 'Admin ?' %>
            <%= check_box_tag 'is_admin', @user.is_admin, value: true%>
            <br /> <br />

            <center><%= submit_tag "Modifier l'utilisateur", class:"btn btn-outline-primary" %></center>
          <% end %>

        </div>
      </div>
    </div>
</body>

app/views/admin/users/index.html.erb
<div class="container" style="margin-top: 100px; width: 24em;" >
  <div class="card">
  <div class="card-body">
    <p><i class="fas fa-users fa-3x mx-3"></i>Utilisateurs actuel : <%= @users.count %></p>
  </div>
</div>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">ID</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Date de creation</th>
      <th scope="col">Modifier</th>
      <th scope="col">Supprimer</th>
    </tr>
  </thead>
  <tbody>

<%  @users.each_with_index do |t,index| %>
    <tr>
      <th scope="row"><% index %></th>
      <td><%= t.id %></td>
      <td><%= t.first_name %></td>
      <td><%= t.last_name %></td>
      <td><%= t.email %></td>
      <td><%= t.created_at %></td>
      <td><%= link_to "Modifier", edit_admin_user_path(t), class:"btn btn-primary" %></td>
      <td><%= link_to "Supprimer", admin_user_path(t.id), class:"btn btn-danger", method: :delete, confirm: "Are you sur ?" %></td>
    </tr>
    <% end %>
  </tbody>
</table>